//This code makes the Led act like it is breathing. So the led goes on and off according to how it is programmed

#define PIN_LED1  2   //define the led pin1
#define PIN_LED2  13  //define the led pin2

//the chn parameter is used to select a specific PWM channel on the microcontroller or platform you are working
//with. PWM channels allow you to independently control multiple PWM signals, each of which can be connected
//to a diffferent output pin

#define CHN1      1   //define the pwm channel1
#define CHN2      2   //define the pwm channel2

//the freq parameter is used to set the frequency of the PWM signal generated by the PWM channel
//In plain context, the value of freq represents how fast the led blinks. As it progresses above 10,20,30... 
//the led becomes too fast fot the human eye to notice the blinks

#define FRQ1      1000  //define the pwm frequency
#define FRQ2      1000  //define the pwm frequency

//at a low frequency, it is also difficult for an iphone camera to detect the blinking rate

#define PWM_BIT1   8    //define the pwm precision
#define PWM_BIT2   12   //define the pwm precision

//the bits parameters serves the purpose of specifying the precision or resolution of the PWM values for a 
//particular PWM channel. The higher the bit value, the smoother the transition. 
//higher bit values however, increase the computational load on the microcontroller

void setup() {
  ledcSetup(CHN1, FRQ1, PWM_BIT1); //setup pwm channel
  ledcSetup(CHN2, FRQ2, PWM_BIT2); //setup pwm channel
  ledcAttachPin(PIN_LED1, CHN1);  //attach the led pin to pwm channel
  ledcAttachPin(PIN_LED2, CHN2);  //attach the led pin to pwm channel
}

void loop() {
  for (int i = 0; i < 255; i++) { //make light fade in
    ledcWrite(CHN1, i);
    ledcWrite(CHN2, i);
    delay(20);
  }
  for (int i = 255; i > -1; i--) {  //make light fade out
    ledcWrite(CHN1, i);
    ledcWrite(CHN2, i);
    delay(20);
  }
  
}
